name = "cubedocs-auth"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cubedocs-auth"
database_id = "db327d85-b8c2-4fed-adaa-25e748778c86"

[vars]
JWT_ISSUER = "https://auth.cubedocs.com"

[[custom_domains]]
pattern = "auth.docs.cubityfir.st"

# Secrets (set via `wrangler secret put`):
#   JWT_SECRET
